### ISSUE TITLE
open with visual studio github

### ISSUE THREAD

**Issue by Evgenbishlee** [DrakiaXYZ/SPT-BigBrain#4]
Hello) The question is as follows: I am trying to edit files from the library.dll, and everything works, but in visual studio on a PC. I need to do this on (the github site), but there is no "open with visual studio github" option on the Code tab. How can I make this choice?

Здравствуйте) Вопрос следующий: пытаюсь отредактировать файлы из .dll и всё получается, Но в visual studio на пк. 
А Мне нужно сделать это на (сайте github), но во вкладке код, отсутствует выбор "open with visual studio github". Как сделать так, чтобы данный выбор был? Объясните пожалуйста на пальцах, что нужно сделать.

![2024-05-03_08-51-50](https://github.com/DrakiaXYZ/SPT-BigBrain/assets/168627102/3ce01233-82c4-4787-93c0-6b10e93afb6e)

**Comment by DrakiaXYZ** [comment]
I've never used web code editing functionality on GitHub, you would need to figure that out using the GitHub documentation. And if it's something that has to be enabled at the repo level, I have no plans on enabling it
