### ISSUE TITLE
1.0.1 is a "Trojan Threat" according to Windows Defender, file download was blocked.

### ISSUE THREAD

**Issue by RainOfPain125** [DrakiaXYZ/SPT-BigBrain#7]
![Screenshot 2024-07-20 005151](https://github.com/user-attachments/assets/ada6dcce-15ec-415e-90e3-7176d3e8428d)

Had to manually allow the download to go through in Windows Security Center despite being flagged as a Trojan. Whether a trojan or not idc lol, please work on not having this occur as it will instantly sus out most players trying to download this mod.

I assume the developer does not run Windows and so did not have this issue. However more interesting, out of me and my two friends - two of us did have Windows Defender flag BigBrain 1.0.1 as trojan malware while the 3rd friend did not. We have no idea why.

**Comment by DrakiaXYZ** [comment]
There's nothing I can do about this, Windows Defender likes to flag new 7z files containing DLLs as Wacatac (We've even had pure typescript server mods get flagged as Wacatac). I've switched the main downloads to .zip files to see if that helps.
